version: "3"
services:
  generic-mock:
    image: generic-mock-native
    # build:
    #   context: .
    ports:
      - "8080:8080"
    environment:
      LOGGING_LEVEL_ROOT: INFO
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
networks:
  default:
    driver: bridge
